### ISSUE TITLE
Unable to open key file

### ISSUE THREAD

**Issue by drrui** [ThreesomeWiki/tencent-course#2]
[hls @ 0000024fa088db00] Skip ('#EXT-X-VERSION:3')
[hls @ 0000024fa088db00] Opening 'D:gittencent-course-masterstaticmp45f719f77key.key' for reading
[hls @ 0000024fa088db00] Unable to open key file D:gittencent-course-masterstaticmp45f719f77key.key
[hls @ 0000024fa088db00] Opening 'crypto:D:\git\tencent-course-master\static\mp4\5f719f77\6.ts' for reading
[hls @ 0000024fa088db00] Opening 'crypto:D:\git\tencent-course-master\static\mp4\5f719f77\9.ts' for reading
[hls @ 0000024fa088db00] Opening 'crypto:D:\git\tencent-course-master\static\mp4\5f719f77\12.ts' for reading
[hls @ 0000024fa088db00] Error when loading first segment 'D:\git\tencent-course-master\static\mp4\5f719f77\6.ts'
copy.m3u8: Invalid data found when processing input

您好。试过几个视频，都是出现差不多的错误。完整的记录如下（copy创建成功之后）：

> 
> copy 创建成功
{ Error: Command failed: cd D:\git\tencent-course-master\static\mp4 && cd 5f719f77 && ffmpeg -allowed_extensions ALL -i copy.m3u8 -c copy new.mp4
ffmpeg version git-2020-08-24-3477feb Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 10.2.1 (GCC) 20200805
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libsrt --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libgsm --enable-librav1e --enable-libsvtav1 --disable-w32threads --enable-libmfx --enable-ffnvcodec --enable-cuda-llvm --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt --enable-amf
  libavutil      56. 58.100 / 56. 58.100
  libavcodec     58.101.100 / 58.101.100
  libavformat    58. 51.100 / 58. 51.100
  libavdevice    58. 11.101 / 58. 11.101
  libavfilter     7. 87.100 /  7. 87.100
  libswscale      5.  8.100 /  5.  8.100
  libswresample   3.  8.100 /  3.  8.100
  libpostproc    55.  8.100 / 55.  8.100
[hls @ 0000019a6022db00] Skip ('#EXT-X-VERSION:3')
[hls @ 0000019a6022db00] Opening 'D:gittencent-course-masterstaticmp45f719f77key.key' for reading
[hls @ 0000019a6022db00] Unable to open key file D:gittencent-course-masterstaticmp45f719f77key.key
[hls @ 0000019a6022db00] Opening 'crypto:D:\git\tencent-course-master\static\mp4\5f719f77\6.ts' for reading
[hls @ 0000019a6022db00] Opening 'crypto:D:\git\tencent-course-master\static\mp4\5f719f77\9.ts' for reading
[hls @ 0000019a6022db00] Opening 'crypto:D:\git\tencent-course-master\static\mp4\5f719f77\12.ts' for reading
[hls @ 0000019a6022db00] Error when loading first segment 'D:\git\tencent-course-master\static\mp4\5f719f77\6.ts'
copy.m3u8: Invalid data found when processing input

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:189:13)
    at maybeClose (internal/child_process.js:970:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
>  killed: false,
 > code: 1,
  signal: null,
  cmd:
   'cd D:\\git\\tencent-course-master\\static\\mp4 && cd 5f719f77 && ffmpeg -allowed_extensions ALL -i copy.m3u8 -c copy new.mp4',
  stdout: '',
  stderr:
   'ffmpeg version git-2020-08-24-3477feb Copyright (c) 2000-2020 the FFmpeg developers\r\n  built with gcc 10.2.1 (GCC) 20200805\r\n  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libsrt --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libgsm --enable-librav1e --enable-libsvtav1 --disable-w32threads --enable-libmfx --enable-ffnvcodec --enable-cuda-llvm --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt --enable-amf\r\n  libavutil      56. 58.100 / 56. 58.100\r\n  libavcodec     58.101.100 / 58.101.100\r\n  libavformat    58. 51.100 / 58. 51.100\r\n  libavdevice    58. 11.101 / 58. 11.101\r\n  libavfilter     7. 87.100 /  7. 87.100\r\n  libswscale      5.  8.100 /  5.  8.100\r\n  libswresample   3.  8.100 /  3.  8.100\r\n  libpostproc    55.  8.100 / 55.  8.100\r\n[hls @ 0000019a6022db00] Skip (\'#EXT-X-VERSION:3\')\r\n[hls @ 0000019a6022db00] Opening \'D:gittencent-course-masterstaticmp45f719f77key.key\' for reading\r\n[hls @ 0000019a6022db00] Unable to open key file D:gittencent-course-masterstaticmp45f719f77key.key\r\n[hls @ 0000019a6022db00] Opening \'crypto:D:\\git\\tencent-course-master\\static\\mp4\\5f719f77\\6.ts\' for reading\r\n[hls @ 0000019a6022db00] Opening \'crypto:D:\\git\\tencent-course-master\\static\\mp4\\5f719f77\\9.ts\' for reading\r\n[hls @ 0000019a6022db00] Opening \'crypto:D:\\git\\tencent-course-master\\static\\mp4\\5f719f77\\12.ts\' for reading\r\n[hls @ 0000019a6022db00] Error when loading first segment \'D:\\git\\tencent-course-master\\static\\mp4\\5f719f77\\6.ts\'\r\ncopy.m3u8: Invalid data found when processing input\r\n' }

**Comment by hanhuizhu** [comment]
看了你的错误，ffmpeg 是不是没有安装

**Comment by hanhuizhu** [comment]
https://zhuanlan.zhihu.com/p/81545814 @drrui

**Comment by drrui** [comment]
@hanhuizhu  额。应该是安装好了的，并且添加到path了。

> D:\z>ffmpeg
ffmpeg version git-2020-08-24-3477feb Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 10.2.1 (GCC) 20200805
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libsrt --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libgsm --enable-librav1e --enable-libsvtav1 --disable-w32threads --enable-libmfx --enable-ffnvcodec --enable-cuda-llvm --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt --enable-amf
  libavutil      56. 58.100 / 56. 58.100
  libavcodec     58.101.100 / 58.101.100
  libavformat    58. 51.100 / 58. 51.100
  libavdevice    58. 11.101 / 58. 11.101
  libavfilter     7. 87.100 /  7. 87.100
  libswscale      5.  8.100 /  5.  8.100
  libswresample   3.  8.100 /  3.  8.100
  libpostproc    55.  8.100 / 55.  8.100
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...

Use -h to get full help or, even better, run 'man ffmpeg'

**Comment by hanhuizhu** [comment]
![image](https://user-images.githubusercontent.com/20557589/91639398-e47a8100-ea48-11ea-9e7a-3da47d50d0c7.png)
好像是你key的地址不对。看看copy.m3u8具体内容

**Comment by hanhuizhu** [comment]
看看你这个目录内容
![image](https://user-images.githubusercontent.com/20557589/91639428-0f64d500-ea49-11ea-8340-3e5810914f39.png)

**Comment by drrui** [comment]
![微信图片_20200829224517](https://user-images.githubusercontent.com/24643117/91639466-636fb980-ea49-11ea-9a05-1c790eb9626e.png)

地址应该是没问题的，在输出的提示中，key的地址有的带有"\"，有的没有"\"，是不是在win下需要转义的问题？

这里的地址中有"\"
> killed: false,
code: 1,
signal: null,
cmd:
'cd D:\git\tencent-course-master\static\mp4 && cd 5f719f77 && ffmpeg -allowed_extensions ALL -i copy.m3u8 -c copy new.mp4',
stdout: '',

但这里又不对了，没有"\"
> [hls @ 0000024fa088db00] Opening 'D:gittencent-course-masterstaticmp45f719f77key.key' for reading
[hls @ 0000024fa088db00] Unable to open key file D:gittencent-course-masterstaticmp45f719f77key.key

**Comment by hanhuizhu** [comment]
看看copy.m3u8,看看`#EXT-X-KEY:METHOD=AES-128,URI`是多少

**Comment by drrui** [comment]
这是m3u8的前几行，地址应该没错

#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:10
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-KEY:METHOD=AES-128,URI="D:\git\tencent-course-master\static\mp4\5f719f77\key.key",IV=0x00000000000000000000000000000000
#EXTINF:10.000000,



![微信图片_20200829224517](https://user-images.githubusercontent.com/24643117/91639466-636fb980-ea49-11ea-9a05-1c790eb9626e.png)

地址应该是没问题的，在输出的提示中，key的地址有的带有"\"，有的没有"\"，是不是在win下需要转义的问题？

这里的地址中有"\"
> killed: false,
code: 1,
signal: null,
cmd:
'cd D:\git\tencent-course-master\static\mp4 && cd 5f719f77 && ffmpeg -allowed_extensions ALL -i copy.m3u8 -c copy new.mp4',
stdout: '',

但这里又不对了，没有"\"
> [hls @ 0000024fa088db00] Opening 'D:gittencent-course-masterstaticmp45f719f77key.key' for reading
[hls @ 0000024fa088db00] Unable to open key file D:gittencent-course-masterstaticmp45f719f77key.key

**Comment by drrui** [comment]
找到这个。。。
https://blog.csdn.net/cquptvlry/article/details/94185316

> 当使用本地的ts和key文件时，m3u8的路径格式是：
> 1、不需要加file:///前缀，直接用路径就可以
> 2、key文件必须是左斜杠/ , ts文件用左斜杠 / 或者 右斜杠 \ 都可以

**Comment by hanhuizhu** [comment]
![image](https://user-images.githubusercontent.com/20557589/91640098-ad5a9e80-ea4d-11ea-96aa-f467c0ad6264.png)
你在 `index.js` line 104,加上`replace(/\\/g,'/')`试试。我这里没有windows，你试试看。

**Comment by drrui** [comment]
@hanhuizhu   success！ 
不过最后的rm命令，得改成win下的等效命令。 或者在git bash下运行。
我在bash下顺利跑完。
再次感谢~

**Comment by hanhuizhu** [comment]
👌，👍
